controllers:
    resource: ../src/Controller/
    type: annotation
api_login_check:
    path: /api/login_check
    methods:  [POST]
gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
# kernel:
#     resource: ../src/Kernel.php
#     type: annotation
